#require_relative '../node_modules/react-native/scripts/react_native_pods'
#require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
#
#platform :ios, '11.0'
#install! 'cocoapods', :deterministic_uuids => false
#
#target 'messengerRN4' do
#  config = use_native_modules!
#
#  # Flags change depending on the env values.
#  flags = get_default_flags()
#
#  use_react_native!(
#    :path => config[:reactNativePath],
#    # to enable hermes on iOS, change `false` to `true` and then install pods
#    :hermes_enabled => flags[:hermes_enabled],
#    :fabric_enabled => flags[:fabric_enabled],
#    # An absolute path to your application root.
#    :app_path => "#{Pod::Config.instance.installation_root}/.."
#  )
#
#  target 'messengerRN4Tests' do
#    inherit! :complete
#    # Pods for testing
#  end
#
#  # Enables Flipper.
#  #
#  # Note that if you have use_frameworks! enabled, Flipper will not work and
#  # you should disable the next line.
#  use_flipper!()
#
#  post_install do |installer|
#    react_native_post_install(installer)
#    __apply_Xcode_12_5_M1_post_install_workaround(installer)
#  end
#end

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'messengerRN4' do
  use_modular_headers!
  config = use_native_modules!
  use_frameworks! :linkage => :static
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec', :modular_headers => false
  pod 'RNFBDatabase', :path => '../node_modules/@react-native-firebase/database'
  $RNFirebaseAsStaticFramework = true
  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change false to true and then install pods
    :hermes_enabled => false
  )

  target 'messengerRN4Tests' do
    inherit! :complete
    # Pods for testing
  end
#  use_frameworks! :linkage => :static
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
#  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  post_install do |installer|
    installer.pods_project.targets.each do |target|
#      react_native_post_install(installer)
      if (target.name&.eql?('FBReactNativeSpec'))
        target.build_phases.each do |build_phase|
          if (build_phase.respond_to?(:name) && build_phase.name.eql?('[CP-User] Generate Specs'))
            target.build_phases.move(build_phase, 0)
          end
        end
      end
    end
  end
end
