export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const IS_LOGGED = 'IS_LOGGED';
export const LOGIN_HAS_ERROR = 'LOGIN_HAS_ERROR';
export const LOGIN_IS_LOADING = 'LOGIN_IS_LOADING';

export const SIGNUP_IS_LOADING = 'SIGNUP_IS_LOADING';
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS';
export const SIGNUP_ERROR ='SIGNUP_ERROR';

export const USER_MAIN_IS_LOADING = 'USER_MAIN_IS_LOADING';
export const USER_MAIN_SUCCESS = 'USER_MAIN_SUCCESS';
export const LIST_USER_IS_LOADING = 'LIST_USER_IS_LOADING';
export const LIST_USER_SUCCESS = 'LIST_USER_SUCCESS';

export const CREATE_CONVERSATION_IS_LOADING = 'CREATE_CONVERSATION_IS_LOADING';